image:
  name: bfieldtools:1.0
  entrypoint: [""]

before_script:
   - Xvfb :99 -screen 0 800x800x8&
   - python setup.py install
   - pip install black
   
stages:
  - Static Analysis
  - Testing

black:
  stage: Static Analysis
  script:
  - black --check .

test:
  stage: Testing
  script:
    - pytest ./tests
    - pytest --cov=bfieldtools ./tests
